name: Deploy PWA

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build PWA
      run: npm run build
      env:
        NEXT_PUBLIC_URL: ${{ secrets.NEXT_PUBLIC_URL }}
        NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
        NEXT_PUBLIC_COLLAGE_API_URL: ${{ secrets.NEXT_PUBLIC_COLLAGE_API_URL }}

    - name: Export static files
      run: npm run export

    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./out

    - name: PWA Quality Check
      run: |
        echo "Checking PWA manifest..."
        if [ -f "./out/manifest.json" ]; then
          echo "✅ Manifest found"
        else
          echo "❌ Manifest missing"
          exit 1
        fi
        
        echo "Checking service worker..."
        if [ -f "./out/sw.js" ]; then
          echo "✅ Service worker found"
        else
          echo "❌ Service worker missing"
          exit 1
        fi
        
        echo "Checking offline page..."
        if [ -f "./out/offline.html" ]; then
          echo "✅ Offline page found"
        else
          echo "❌ Offline page missing"
          exit 1
        fi
        
        echo "✅ PWA build quality check passed!"
